
# Your tiktok @user:
tiktok_user: "@..."

# Server IP, RCON port and password
# All of these can be found on your server.properties
host: '0.0.0.0'
port: 00000
senha: 'password'


# Likes
likes: True # Activates or deactivates this module
quantidade_likes: 300 # Number of likes required to run the command
cmd_like:
  - 'say {name} sent 300 likes!'
  - 'execute at @a run summon minecraft:zombie ~ ~ ~ {{CustomName:"\"{name}\"",CustomNameVisible:1b}}'


# Share (1 per user):
share: True # Activates or deactivates this module
cmd_share:
  - 'say {name} shared the live!'
  - 'execute at @a run summon minecraft:allay ~ ~ ~ {{CustomName:"\"{name}\"",CustomNameVisible:1b}}'


# Comments
comment: True # Activates or deactivates this module
cmd_comment:
  - 'say {name}: {comment}'


# Follow (1 per user):
follow: True # Activates or deactivates this module
cmd_follow:
  - 'say {}'
  - 'execute at @a run summon minecraft:fox ~ ~ ~ {{CustomName:"\"{name}\"",CustomNameVisible:1b}}'


# Website with all the IDs
# https://streamdps.com/tiktok-widgets/gifts

# Gifts:
gift: True # Activates or deactivates this module
presentes:
  - id: 5655
    cmd:
      - 'say {name} sent a Rose!'
      - 'execute at @a run summon minecraft:creeper ~ ~ ~ {{CustomName:"\"{name}\"",CustomNameVisible:1b}}'
  - id: 6652
    cmd:
      - 'say {name} sent a Lightning Bolt!'
      - 'execute at @a run summon minecraft:skeleton ~ ~ ~ {{CustomName:"\"{name}\"",CustomNameVisible:1b}}'
  #- id: Add as many as you want.
  #  cmd:
  #    - 'And as many commands as you want'
